### ISSUE TITLE
I can't run it offline

### ISSUE THREAD

**Issue by MrBenzWorld** [enricoros/big-AGI#334] opened 2024-01-08 08:51 UTC
How can I run it offline? 

npm install
npm run dev is 
 After this, 

-Local : http://local host:3000 is ready,  
But nothing is visible when I use this link. Could you please tell me if I missed something.

**Comment by enricoros** [comment] 2024-01-08 09:14
@MrBenzWorld can you provide a screenshot? don't know if this is on windows/mac, or chrome/safari/firefox, etc.

Can you also open the console (F12 on Chrome, and then 'Console') and let me know what are the error messages?

**Comment by MrBenzWorld** [comment] 2024-01-08 09:31
@enricoros 
Thank you for your response. 

I think, vercel web analytics failed to load, please disable all analytics for offline run, 

I'm using windows 11 , it is running when I connect to the internet, but not running when I'm offline. 

Also, I found that some depreciated . please find images below. 


![IMG_20240108_132324.jpg](https://github.com/enricoros/big-AGI/assets/113277019/d665e6ca-0a02-47df-af9c-cba6b7bb400e)

![IMG_20240108_132409.jpg](https://github.com/enricoros/big-AGI/assets/113277019/ef26c0b5-3c5a-46f7-a84c-b28227f0ff0c)

**Comment by enricoros** [comment] 2024-01-08 10:03
Thanks, no worries about the deprecated (I'm on that thread) and the Vercel (shall not be a problem at all).

What worries me is the first main:1 error.

The application does 1 round-trip to its own backend (in your case localhost:3000) and I believe that call may be blocked.


Let me explain how Big AGI's architecture works:

 1. Browser loads html/JS (the web UI)
 2. Browser calls the backend (localhost:3000) every time it needs to make an LLM call (e.g. calling OpenAI, or Ollama, etc.) - this is because apps that make all requests from the browser will face CORS issues
 3. The big Agi backend (localhost:3000) calls the 3rs party service (e.g. OpenAI API)

The above is all in the GitHub code, very open.

How are you "disconnecting" the Big-AGI app? I can try to reproduce your environment and find the issue. However I don't think it's going to be an easy solution, as there's not much to do Offline (at least the Backend needs to be accessible).

If you want to try without the vercel, quickly comment the 2 Vercel lines on pages/_app.tsx and build/run again. Also you can use "npm run dev" instead of build+run, for running in development mode, with more debug on errors.

**Comment by enricoros** [comment] 2024-01-08 10:04
Thanks, no worries about the deprecated (I'm on that thread) and the Vercel (shall not be a problem at all).

What worries me is the first main:1 error.

The application does 1 round-trip to its own backend (in your case localhost:3000) and I believe that call may be blocked.


Let me explain how Big AGI's architecture works:

 1. Browser loads html/JS (the web UI)
 2. Browser calls the backend (localhost:3000) every time it needs to make an LLM call (e.g. calling OpenAI, or Ollama, etc.) - this is because apps that make all requests from the browser will face CORS issues
 3. The big Agi backend (localhost:3000) calls the 3rs party service (e.g. OpenAI API)

The above is all in the GitHub code, very open.

How are you "disconnecting" the Big-AGI app? I can try to reproduce your environment and find the issue. However I don't think it's going to be an easy solution, as there's not much to do Offline (at least the Backend needs to be accessible).

If you want to try without the vercel, quickly comment the 2 Vercel lines on pages/_app.tsx and build/run again.

**Comment by MrBenzWorld** [comment] 2024-01-08 12:30
@enricoros 
Thank you for the detailed comments. 

In offline, 
1.Chrome is blocking , LibreWolf is working well. 

2.Working professionals must disconnect the internet in some conditions. 

3. Also, once I ask you a question, I can't stop it in the middle of generation.

**Comment by enricoros** [comment] 2024-01-09 02:06
Hi, I've tried to reproduce this, disconnecting my PC fully and running `npm run dev` and then opening a new window (in incognito, so there's no state):

![image](https://github.com/enricoros/big-AGI/assets/32999/6643282b-4135-4912-baf6-396c8ebd9546)

As you can see, this is working. All I did was: 1. disconnect, 2. `npm run dev`, 3. open a chrome incognito window, 4. load localhost:3000.

This is the networking log, where you can see the 2 connections to Vercel correctly blocked, but everything else is working.

![image](https://github.com/enricoros/big-AGI/assets/32999/f5540e95-0575-468d-b199-d6bfdcebfcab)

Do you see other server/browser logs, or can you show your networking connections log as mine above? This lacks reproducibility at the moment.

**Comment by MrBenzWorld** [comment] 2024-01-09 10:32
@enricoros , 

1. I have tried on 5 browsers with offline. (npm run dev)

- Firefox, Libre Wolf  working 
- Chrome, Edge, Brave is not working.

Firefox
![Firefox](https://github.com/enricoros/big-AGI/assets/113277019/404e5bd2-1d1c-45f2-adec-73244e61e1e0)

Chrome
![Google Chrome](https://github.com/enricoros/big-AGI/assets/113277019/7dc67ab6-f50b-453a-b492-e06e4b073be3)

3. Main intention is , it should work with no internet (offline)
4. Another way, when i build it "npm run build", it is not successful. i think is connecting for google fonts when I'm trying build it manually. 

Thank you.

**Comment by enricoros** [comment] 2024-01-09 12:41
I see a chrome screenshot, but there's really nothing. Can you have a more comprehensive screenshot?

I provided mine: it shows the network connections, the browser console, and the terminal. Please send me a full screen capture with those 3, and make sure you refresh chrome with Shift+F5.

There 'have to be' some connections (even interrupted/aborted) in Chrome.

**Comment by enricoros** [comment] 2024-01-16 00:31
@MrBenzWorld please let me know where this issue stands. There is not enough information to reproduce this issue, and much time has been spent to confirm that this is indeed working.

**Comment by MrBenzWorld** [comment] 2024-01-16 08:01
@enricoros , Thank you for 1.11 version update, also i appreciate your efforts for build a better application. Thank you again considering my request. 

with 1.11 version,  complete offline:
here i have added some screenshots, Firefox is working , chrome, Microsoft edge is not working,  I'm using Kaspersky antivirus.  windows 11 pro. 

![chrome incongnito mode alos not working](https://github.com/enricoros/big-AGI/assets/113277019/27f9843c-0700-474f-a88b-c34e749b861f)
![chrome1](https://github.com/enricoros/big-AGI/assets/113277019/5b79ba20-808f-4f29-bda6-c34a0c4383d5)
![chrome2](https://github.com/enricoros/big-AGI/assets/113277019/54c41a52-b23f-4705-b888-de285e6fb41e)
![chrome3 network](https://github.com/enricoros/big-AGI/assets/113277019/6162486b-32dc-45cd-8626-3db124d4e7e5)
![chrome4 application](https://github.com/enricoros/big-AGI/assets/113277019/e3d427ae-edab-4e74-9890-c34eb085a28c)
![chrome5 if i allow 3rd party cookies](https://github.com/enricoros/big-AGI/assets/113277019/97621cf3-3da0-4472-b7b7-325b1dee9b2e)
![chrome5 if i allow 3rd party cookies2](https://github.com/enricoros/big-AGI/assets/113277019/1d9bdc50-e533-462f-8550-bd4cd98d591c)
![chrome5 if i block 3rd party cookies2](https://github.com/enricoros/big-AGI/assets/113277019/418610a3-dc2d-4d40-a355-cb0d9fcd45b8)
![edge 1](https://github.com/enricoros/big-AGI/assets/113277019/46439967-3dc8-44d6-a739-2c4a769e83ee)
![firefox working](https://github.com/enricoros/big-AGI/assets/113277019/b0c99b94-80f5-4154-8dbc-3cade90b7deb)
![firfox working](https://github.com/enricoros/big-AGI/assets/113277019/59a18afb-0908-41a7-a9ec-1adbb135d830)

**Comment by enricoros** [comment] 2024-01-16 13:06
Thansk @MrBenzWorld. The signal it's working on Firefox is that ">> Query #1 ..." string. When that is happening, I know the application runs well, but doesn't happen in Chrome.

**1. Can you try Chrome in an Incognito window, and see what's different?**

Also the following screenshot is interesting, are you able to expand it so all the resources are visible, and close ("X" button) the inspection on the CSS file, so I can see the full information on all the requests:
![image](https://github.com/enricoros/big-AGI/assets/32999/24af9182-79fd-4cff-9225-6b24f37fc34d)

**2. re-take this screenshot of Chrome with more area and closing the single-resource panel "X"**

**3. Disable Kaspersky (seems to have a Chrome Extension that gets in the way) and retry**

Thanks

**Comment by enricoros** [comment] 2024-01-23 09:54
Closing this due to missing information not provided, and extensive time reproducing this that failed.

**Comment by enricoros** [comment] 2024-01-23 09:55
Closing this due to missing information not provided, and extensive time reproducing this that failed.

**Closed by enricoros** 2024-01-23 09:55 UTC
Labels: requested-info

**Comment by enricoros** [comment] 2024-03-05 05:40
@MrBenzWorld found the culprit - resolved in ed333c05134b81cff890d5a72ae5e66308a78a32. Will be out soon.

**Comment by MrBenzWorld** [comment] 2024-03-05 05:55
> @MrBenzWorld found the culprit - resolved in ed333c05134b81cff890d5a72ae5e66308a78a32. Will be out soon.

Thank you very much. I appreciate your efforts and product development.
