### ISSUE TITLE
[Roadmap] Allow to add customizable persona 

### ISSUE THREAD

**Issue by kevinarch** [enricoros/big-AGI#534] opened 2024-05-10 12:51 UTC
**Why**
Currently, there is no option to define reusable personas. As a workaround, I create a new chat with a custom prompt and mark it as a "Favorite" to reuse it later. However, this approach has some limitations.

**Description**
Adding a separate section in the settings(?) to manage custom personas. This feature would enable users to create, edit, and remove personas as needed.

**Requirements**
To enhance flexibility, it would be beneficial to allow users to set a persona's avatar using either a remote image URI or an emoji

**Comment by enricoros** [comment] 2024-05-10 23:52
Agree it's important, but also widely covered in the Roadmap: https://github.com/users/enricoros/projects/4/views/2?filterQuery=is%3Aissue%2Cpr+label%3A%22New+Personas%22

Marking as duplicate of #35

**Closed by enricoros** 2024-05-10 23:52 UTC
