### ISSUE TITLE
[Roadmap] Option to add and save cutom prompts

### ISSUE THREAD

**Issue by kk-rishang** [enricoros/big-AGI#326] opened 2024-01-06 06:22 UTC
**Why**
Right now we have option to save one custom prompt, i will like to have many for different scenarious

**Requirements**
We can store data in browser local storage for prompts and use it from there

**Comment by enricoros** [comment] 2024-01-09 02:55
Good, but duplicate of #35 - marking as duplicate for now.

**Closed by enricoros** 2024-01-09 02:55 UTC
