### ISSUE TITLE
[BUG] list formatting skips a line often

### ISSUE THREAD

**Issue by agdfoster** [enricoros/big-AGI#404] opened 2024-02-07 16:49 UTC
### Description

![CleanShot 2024-02-07 at 16 47 51@2x](https://github.com/enricoros/big-AGI/assets/5314171/a9892962-6b47-4612-b2d2-d8e41f73ac35)

^^ This happens regularly. No big deal but numbered lists, the number often doesn't align with the start of their item.

### Device and browser

Mac App Vercel.

### Screenshots and more

![CleanShot 2024-02-07 at 16 47 51@2x](https://github.com/enricoros/big-AGI/assets/5314171/452ccd41-6a83-441e-9a51-0374dd959551)

### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment] 2024-02-07 17:10
@agdfoster could you copy and paste the exact text? Also please let me know if this is with Markdown rendering enabled or disabled (in Preferences).

**Comment by enricoros** [comment] 2024-02-16 22:55
Closing because cannot reproduce: didn't receive the input text to replicate, and never experienced (maybe with a different net)

**Closed** 2024-02-16 22:55 UTC
Labels: type: bug, requested-info
