### ISSUE TITLE
[BUG] Vercel database stopped working with update to 1.7.x

### ISSUE THREAD

**Issue by tdpires** [enricoros/big-AGI#277] opened 2023-12-14 18:52 UTC
Hello,

Running the docker image of Big-AGI and had a postgres DB on Vercel storage for the sharing feature. It was working in version 1.6 for us, but after moving to 1.7.1, it stopped working. Getting this error when trying to make a link (menu > Share/Export > Share on big-AGI):
```
[ { "code": "invalid_type", "expected": "object", "received": "undefined", "path": [], "message": "Required" } ]
```
![Screenshot 2023-12-14 at 1 53 16 PM](https://github.com/enricoros/big-AGI/assets/90480825/475df6ec-1a61-4384-9602-0b7b5e07a026)

This is my .env file connection strings:
```
POSTGRES_PRISMA_URL="postgres://USERNAME:PASSWORD@ep-dark-cake-XXXXXXXX-pooler.us-east-1.postgres.vercel-storage.com:5432/verceldb?pgbouncer=true&connect_timeout=15"
POSTGRES_URL_NON_POOLING="postgres://USERNAME:PASSWORD@ep-dark-cake-XXXXXXXX.us-east-1.postgres.vercel-storage.com:5432/verceldb"
```

Already dropped DB tables, did `npx prisma generate` from the schema to rebuild tables from scratch. Any ideas? Thanks!

**Comment by enricoros** [comment] 2023-12-15 23:57
I just tested on:
 - localhost: ok
 - get.big-agi.com (open-source freely hosted): ok

The connection string is really similar for me (I just used the vercel integration, an the only difference is that both variables end with /verceldb - while one of yours has extra params).

Could you try with a [different container](https://github.com/enricoros/big-AGI/pkgs/container/big-agi)?
 - e.g big-agi:latest
 
 I don't know whether this is a docker issue, as the issue is not present on Vercel and local development.
 You can also try with your DB env vars on local dev (`npm i && npm run build && npm run start`) to see if it works well.

**Comment by enricoros** [comment] 2023-12-18 20:47
Tried again and cannot reproduce - please let me know @tdpires, otherwise I'll close this.

**Comment by tdpires** [comment] 2023-12-18 21:40
thank you, i will try your suggestion

**Comment by tdpires** [comment] 2023-12-18 21:41
i suspect it may be a docker issue.

**Comment by enricoros** [comment] 2023-12-18 23:05
I'll try on docker now.

**Comment by enricoros** [comment] 2023-12-18 23:22
I've relaxed the URL validation, just in case, but it's working for me.

# Container parameters
![image](https://github.com/enricoros/big-AGI/assets/32999/6121e704-24e1-40ea-a04a-44c1e20cae3c)

# Result
![image](https://github.com/enricoros/big-AGI/assets/32999/445480ce-69b0-418d-b88d-59a8d4889566)

As you can see, docker works as well (this is with a newly pulled :latest big-agi).

Did you also run
`npx prisma db push` after setting the 2 env vars, so that table structure will be created?

Please let me know, but I'm inclined to close this task, as it works well across environments for me.

**Comment by tdpires** [comment] 2023-12-19 00:52
Not sure if this matters, but I am using docker compose and changed the port to 3001 (because of a conflict). My docker compose file looks like:

```
version: '3.9'

services:
  big-agi:
    image: ghcr.io/enricoros/big-agi:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: [ "next", "start", "-p", "3000" ]
```

**Comment by enricoros** [comment] 2023-12-19 02:37
Ok, trying this.

**Comment by enricoros** [comment] 2023-12-19 02:44
Works with your docker-compose.yaml, just tried:
![image](https://github.com/enricoros/big-AGI/assets/32999/fea8533b-a261-4377-b370-afbf3370e02e)

![image](https://github.com/enricoros/big-AGI/assets/32999/effa2804-b5a0-4ecb-9513-14b1c5b4a8ba)

Can you try again and let me know your issue? It's been working on every possible way for me.

**Comment by tdpires** [comment] 2023-12-20 16:08
Yeah seems to be a Zod error. i can do a DB push from the server to build the schema but the docker, while it connects, isn't able to write anything. Firewall on the host machine is open to those ports as is the docker network

**Comment by enricoros** [comment] 2023-12-20 19:44
Very weird. I'm inclined to close this issue tho, as I don't believe is the code of big-AGI but rather some other configuration mystery.

**Comment by enricoros** [comment] 2023-12-28 11:05
Closing: could not replicate despite trying hard.

**Closed by enricoros** 2023-12-28 11:05 UTC
