### ISSUE TITLE
Sometimes streamming request is canceled

### ISSUE THREAD

**Issue by webmaster223** [enricoros/big-AGI#391] opened 2024-02-04 04:25 UTC
### Description

I am using call function in big-agi and it sometimes make streamming api issue when I am talking

### Device and browser

Chrome

### Screenshots and more

![image](https://github.com/enricoros/big-AGI/assets/97944031/7af6794a-9b2b-4324-9740-f11f5e78bf87)

### Willingness to Contribute

- [X] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment] 2024-02-04 04:27
Please add details on how to reproduce this. In the code there's automatic cancellation of the request to streaming IF the user says something before the former stream has ended. This is like people interrupting when they talk.

This could be normal.

**Comment by enricoros** [comment] 2024-02-22 18:45
Closing - cannot reproduce. May as well be that when one starts talking ,the stream request is interrupted (correctly) as people do that.

**Closed by enricoros** 2024-02-22 18:45 UTC
Labels: requested-info
