### ISSUE TITLE
Allow saving custom AI purpose

### ISSUE THREAD

**Issue by PaRaD1SE98** [enricoros/big-agi#97] opened 2023-04-26 19:55 UTC
It would be nice if we can save custom purpose.

**Comment by enricoros** [comment] 2023-04-27 01:00
How do you envision the UX to be? Asking because there are many ways to do it, and only want to do it right.

**Comment by PaRaD1SE98** [comment] 2023-04-27 08:17
I think a suitable example is the home page of google chrome. The current layout is already close.

![image](https://user-images.githubusercontent.com/78383353/234778958-974c3cf9-1808-4fac-8143-111277bd42f7.png)

I think we can modify the current 'edit-show' feature to a 'pin' feature.

We can have an 'options' button on the top right of every purpose item like this. (On hover show 'options' button)

![image](https://user-images.githubusercontent.com/78383353/234780439-41f2a0b0-c057-45c4-96f1-8e7f0be56683.png)

Inside the options we can have :

- 'pin' or something like 'stay on top', 
- 'modify' to adjust icon and prompt
- 'delete' to delete the item

May be we also need a bulk delete button somewhere.

Instead of an 'edit' button here, we can have a 'Show <More/Less>...' button.(Or put it on the bottom right...)
Always keep the 'Custom' on the last 'pinned' purpose items.
(Or don't use 'Custom purpose item' but add an 'add' button somewhere)
Maybe add a scroll bar to keep the ui clean.
![image](https://user-images.githubusercontent.com/78383353/234785322-d6b48821-5c69-44a1-90e7-40dce9527ace.png)

For the save purpose feature, it could be like this:
![image](https://user-images.githubusercontent.com/78383353/234788235-96aef1c9-7672-4e47-9987-9d9d0102ccb9.png)
on save, add the feature to the first 'pinned' feature.

**Comment by enricoros** [comment] 2023-04-27 11:21
Thanks for the great guidance - very appreciated your diagrams - very clear.
I will consider it. Need to figure out how to overlay:
 - user edited > source-edits (people that customize this app) > default options.

Right now the "Purposes" system is very hardcoded, so people edit them in the code and then deploy their own. But it should be editable after deployment by each user, that's for sure.

**Comment by enricoros** [comment] 2023-04-27 20:23
#35

**Comment by enricoros** [comment] 2023-11-16 05:24
Duplicate of: https://github.com/enricoros/big-agi/issues/35

**Closed by enricoros** 2023-11-16 05:24 UTC
