### ISSUE TITLE
[BUG] v2 Branch Production Build Fails Due to TypeScript Error

### ISSUE THREAD

**Issue by git-anish** [enricoros/big-AGI#686] opened 2024-12-01 21:00 UTC
### Description

The production build (`npx next build`) fails with a TypeScript type mismatch in `attachment.pipeline.ts`. This issue does not occur in the development environment (`npm run dev`), likely due to lenient type checking in development mode.

**Steps to Reproduce**  
1. Use Node.js version `18.18.0`.
2. Install dependencies and clear npm cache:
   ```bash
   npm cache clean --force
   npm install --include=optional sharp



### Device and browser

Running on an Ampere server with ubuntu

Environment Details

Node.js: v18.18.0
npm: v9.8.1
OS: Ubuntu (Linux ARM)
Next.js: 15.0.2

### Screenshots and more

![image](https://github.com/user-attachments/assets/a31cdf69-a67f-434f-a40e-c5a8ea6d4daa)


### Willingness to Contribute

- [ ] 🙋‍♂️ Yes, I would like to contribute a fix.

**Comment by enricoros** [comment] 2024-12-07 21:15
@git-anish fixed last week https://github.com/enricoros/big-AGI/commit/e5870e43ceb95142d5f7d27de964a4b3fa8dae7a on the v2-dev branch.

**Comment by git-anish** [comment] 2024-12-07 22:53
Hi @enricoros !thank you for getting back to me

I tried to building it 18 hours ago [on my fork](https://github.com/git-anish/big-AGI/actions/runs/12209914026/job/34065349727) with all the latest commits had a similar fail using the actions workflow, will try compiling locally and get back to you

![Screenshot 2024-12-07 at 2 51 29 PM](https://github.com/user-attachments/assets/c9c8e87a-e5b6-4958-ace3-86b63533c466)

**Comment by git-anish** [comment] 2024-12-07 23:22
Interesting, it failed again with the same error on my fork via build actions (I did sync the forks & built v2-dev) & locally as well (did a fresh git clone)

By any chance could you upload your arm prod build docker images? no worries if its too much at the moment! I can continue running it via npm run dev

![Screenshot 2024-12-07 at 3 19 32 PM](https://github.com/user-attachments/assets/22f5b179-d95b-47c3-82a0-b6ee9a559001)

**Comment by enricoros** [comment] 2024-12-11 05:13
I've fixed a few long standing issues in v2-dev, tried every way but cannot reproduce the draw.js CustomEvent issue. closing

**Closed by enricoros** 2024-12-11 05:13 UTC
Labels: type: bug

**Comment by git-anish** [comment] 2024-12-12 14:23
Hey, yes I was referring to v2 docker images - any ETA on those?

Still continuing to get the errors when building both on my local machine and on github actions, not important to me personally so perfectly with closing this ticket. Thank you for attempting to look in to it!

**Comment by enricoros** [comment] 2024-12-13 01:37
@git-anish end of month. also the big-agi.com hosted version will receive a large overhaul and will be my focus.
